#cloud-config
groups:
  - developer  # Group must be explicitly created before referencing

users:
  - name: developer
    gecos: Developer User
    primary_group: developer
    groups: sudo  # Add to sudo group instead of using users group
    lock_passwd: false
    passwd: $6$wpbQUw94OGm6bBl9$RQ2tiPm2fwfIqZ0lgrPTN4NhZeoTh8EYjr6S2pPu5jeY7dtI5715.megFvANhPNsaAnznl.7KDYYBpEK8lGkw0  # echo maldev@25 | mkpasswd -m sha-512 -s"
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDOBRs6FZuKGrp/NLf6PTbb1Yq3Hr0vFWIoRN9YKB5D0uY9WoO+TcQWrspkn+S17QowqbnjFjlYDte35u1Kcr4du0P12bqNyCM8yag/TVEfXBgr5HwteOBfrtXK7Zo2K1L4KvTNgv4x1uDLla6UIXEPChK+P/XmRrNLEQbx3Y9slup6ABLMSDbOGMVrxMKpHqpkhOkjvQ0YF9zjBwvQG8br86uPz0FdpMOvprqm2FEGM0GEFaNiVWlwiy8OtX8IZTJFOWZmAGjopiFS2b+AhBwd4+My80rmDwrLu2DBvETP+GUJ4GGkj3b03uPjNwZoOicMOtUh3QczK94SC6ajBnaVYtcEKryomXIQllR+WJzJHz6sIV7q3NPqaehx1j/WUYX1jVWcwhyGKTssS35rnAF07R+9tNd1cUoTX2tXpfqHt/rsBApfi7PSwu6/R4wh8PVldYbSk68zE9U/y+JlVOmmJsEGCI9TEsVcpDS8aX3KhmPgTpLyijskslZtI/trgMzydf1lpWF8fs9Xh/twBAbFTb5C600JVSPXwKuxRDo+YxT8ouv9yoyIZV+gwesv90L1RaHZy61zumm8CqOklKDTFens/V6vQOYj0OeaFHuB6hpKbpeyCyEPIaIRzNN2LHBKFIn3vm9/kPF679YOOFjsdo6AFctLj3LOAGo72b5uDw== mail@anir0y.in

package_update: true
package_upgrade: true

packages:
  - gcc
  - g++
  - gdb
  - make
  - cmake
  - libboost-all-dev
  - libssh-dev
  - libpqxx-dev
  - postgresql-all
  - libcryptopp-dev

runcmd:
  - echo "Cloud-init started at $(date)" >> /var/log/cloud-init-debug.log
  - echo "Cloud-init finished at $(date)" >> /var/log/cloud-init-debug.log
  - echo "System boot completed at $(date)" >> /var/log/cloud-init-debug.log
final_message: "System boot completed after $UPTIME seconds"